/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package depo_otomasyonu;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author talha
 */
public class Customer_add extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Customer_add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MüşteriEkle_button = new javax.swing.JButton();
        adres_text = new javax.swing.JTextField();
        username_text = new javax.swing.JTextField();
        eposta_text = new javax.swing.JTextField();
        soyad_text = new javax.swing.JTextField();
        isim_text = new javax.swing.JTextField();
        isim_label = new javax.swing.JLabel();
        soyad_label = new javax.swing.JLabel();
        adres_label = new javax.swing.JLabel();
        username_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        eposta_label = new javax.swing.JLabel();
        password_text = new javax.swing.JPasswordField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Müşteri Kayıt Formu");
        setBounds(new java.awt.Rectangle(0, 0, 600, 500));
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        MüşteriEkle_button.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        MüşteriEkle_button.setText("KAYIT OL");
        MüşteriEkle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MüşteriEkle_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(MüşteriEkle_button);
        MüşteriEkle_button.setBounds(190, 400, 150, 50);

        adres_text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adres_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adres_textActionPerformed(evt);
            }
        });
        getContentPane().add(adres_text);
        adres_text.setBounds(280, 150, 200, 35);

        username_text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(username_text);
        username_text.setBounds(280, 210, 200, 35);

        eposta_text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(eposta_text);
        eposta_text.setBounds(280, 330, 200, 35);

        soyad_text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        soyad_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soyad_textActionPerformed(evt);
            }
        });
        getContentPane().add(soyad_text);
        soyad_text.setBounds(280, 90, 200, 35);

        isim_text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(isim_text);
        isim_text.setBounds(280, 30, 200, 35);

        isim_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        isim_label.setText("Adınız:");
        getContentPane().add(isim_label);
        isim_label.setBounds(60, 30, 140, 40);

        soyad_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        soyad_label.setText("Soyadınız:");
        getContentPane().add(soyad_label);
        soyad_label.setBounds(60, 90, 140, 40);

        adres_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adres_label.setText("Şehir:");
        getContentPane().add(adres_label);
        adres_label.setBounds(60, 150, 140, 40);

        username_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username_label.setText("Kullanıcı Adı:");
        getContentPane().add(username_label);
        username_label.setBounds(60, 210, 140, 40);

        password_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        password_label.setText("Şifre:");
        getContentPane().add(password_label);
        password_label.setBounds(60, 270, 140, 40);

        eposta_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eposta_label.setText("E-Posta");
        getContentPane().add(eposta_label);
        eposta_label.setBounds(60, 330, 140, 40);

        password_text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        password_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_textActionPerformed(evt);
            }
        });
        getContentPane().add(password_text);
        password_text.setBounds(280, 270, 200, 35);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/depo_otomasyonu/background.jpg"))); // NOI18N
        Background.setText("jLabel1");
        Background.setMaximumSize(new java.awt.Dimension(600, 500));
        Background.setMinimumSize(new java.awt.Dimension(600, 500));
        Background.setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 600, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soyad_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soyad_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soyad_textActionPerformed

    private void MüşteriEkle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MüşteriEkle_buttonActionPerformed
        // TODO add your handling code here:
        String cFname = isim_text.getText();
        String cLname = soyad_text.getText();
        String cAdress = adres_text.getText();
        String cUsername = username_text.getText();
        String cPassword = password_text.getText();
        String cEmail = eposta_text.getText();

        if(cFname.equals("") || cLname.equals("") || cAdress.equals("") || cUsername.equals("") || cPassword.equals("") || cEmail.equals("")){
    
        JOptionPane.showMessageDialog(this, "Lütfen Boş Alanları Doldurunuz!");
    }
        else{
        try{        

            Class.forName("oracle.jdbc.OracleDriver");
            Statement st;
            ResultSet rs=null;

            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/XEPDB1","SYSTEM","1124");
            st= con.createStatement();

            String sql = "INSERT INTO CUSTOMER (cFname,cLname,cAdress,cUsername,cPassword,cEmail)"
            + " VALUES ('"+cFname+"', '"+cLname+"', '"+cAdress+"', '"+cUsername+"','"+cPassword+"','"+cEmail+"')";

            st.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(null, "Müşteri Eklendi!");

        }
        catch(ClassNotFoundException ex){
            
            JOptionPane.showMessageDialog(null, "Müşteri Eklenemedi!");

        } catch (SQLException ex) {
            Logger.getLogger(Customer_add.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Müşteri Eklenemedi!");
        }
        }
    }//GEN-LAST:event_MüşteriEkle_buttonActionPerformed

    private void adres_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adres_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adres_textActionPerformed

    private void password_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton MüşteriEkle_button;
    private javax.swing.JLabel adres_label;
    private javax.swing.JTextField adres_text;
    private javax.swing.JLabel eposta_label;
    private javax.swing.JTextField eposta_text;
    private javax.swing.JLabel isim_label;
    private javax.swing.JTextField isim_text;
    private javax.swing.JLabel password_label;
    private javax.swing.JPasswordField password_text;
    private javax.swing.JLabel soyad_label;
    private javax.swing.JTextField soyad_text;
    private javax.swing.JLabel username_label;
    private javax.swing.JTextField username_text;
    // End of variables declaration//GEN-END:variables
}
