/*
* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package depo_otomasyonu;

/**
 *
 * @author talha
 */
import static depo_otomasyonu.Customer_Login.customerid;
import static depo_otomasyonu.Customer_Login.username;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Manager_Login extends javax.swing.JFrame {

    public static String username;
    public static int mID;
    public static String sehir;
    
    public Manager_Login() {
        initComponents();           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        password_text = new javax.swing.JPasswordField();
        username_text = new javax.swing.JTextField();
        login_button = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yönetici Giriş Formu");
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        username_label.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        username_label.setText("KULLANICI ADI");
        getContentPane().add(username_label);
        username_label.setBounds(80, 60, 120, 50);

        password_label.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        password_label.setText("ŞİFRE");
        getContentPane().add(password_label);
        password_label.setBounds(80, 170, 120, 50);

        password_text.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(password_text);
        password_text.setBounds(270, 170, 150, 50);

        username_text.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(username_text);
        username_text.setBounds(270, 60, 150, 50);

        login_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        login_button.setText("GİRİŞ YAP");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(login_button);
        login_button.setBounds(170, 290, 117, 60);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/depo_otomasyonu/background.jpg"))); // NOI18N
        Background.setMaximumSize(new java.awt.Dimension(500, 400));
        Background.setMinimumSize(new java.awt.Dimension(500, 400));
        Background.setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 500, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
       String mUsername=username_text.getText();
       String mPassword=password_text.getText();
       String a = "Hoşgeldiniz";

        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String sql = "SELECT * FROM Manager Where mUsername='"+username_text.getText()+"' and mPassword='"+password_text.getText()+"'";
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/XEPDB1","SYSTEM","1124");
            CallableStatement cs = con.prepareCall("{call LOGİN_MPROC(?,?,?)}");
            cs.registerOutParameter(1, java.sql.Types.INTEGER);
            cs.setString(2, mUsername);
            cs.setString(3, mPassword);
            cs.executeUpdate();
           if(cs.getInt(1)==0){
               JOptionPane.showMessageDialog(null, "YANLIŞ KULLANICI ADI VEYA ŞİFRE!!!");
            }
            else{
               // JOptionPane.showMessageDialog(null, "BAŞARILI!!");
                PreparedStatement ps = con.prepareStatement(sql);      
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                 //JOptionPane.showMessageDialog(null,"BAŞARILI GİRİŞ!!!"); 
                 JOptionPane.showMessageDialog(null, rs.getString("mFname"), a, HEIGHT);                
                 username = rs.getString("mUsername");
                 mID = rs.getInt("mID");
                 sehir = rs.getString("Cty");
                 ManagerPanel managerpanel = new ManagerPanel();
                 rs.close();
                 con.close();
                 managerpanel.show();
                 this.hide();
             }
            }  

        }
        catch(ClassNotFoundException ex){

        } catch (SQLException ex) {
            Logger.getLogger(Manager_Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "HATALI İŞLEM!!!");
        }           // TODO add your handling code here:
    }//GEN-LAST:event_login_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton login_button;
    private javax.swing.JLabel password_label;
    private javax.swing.JPasswordField password_text;
    private javax.swing.JLabel username_label;
    private javax.swing.JTextField username_text;
    // End of variables declaration//GEN-END:variables
}
